//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_costcenters
    {
        public int Ide_CostCenter { get; set; }
        public string Cod_CostCenter { get; set; }
        public string Nom_CostCenter { get; set; }
        public string Ide_ParentCostCenter { get; set; }
    }
}
