//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_extencionessubcriber
    {
        public int Id_Extencionessubcriber { get; set; }
        public string Nom_Subscriber { get; set; }
        public string Extencion { get; set; }
        public int Ide_CostCenter { get; set; }
        public int Id_Area { get; set; }
        public int IdSucursal { get; set; }
    }
}
