//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_ipc_communicationhistory
    {
        public string id { get; set; }
        public string answeringPartyName { get; set; }
        public string buttonNumber { get; set; }
        public string cLIName { get; set; }
        public string cLINumber { get; set; }
        public string callType { get; set; }
        public string callUsage { get; set; }
        public string connectionId { get; set; }
        public string destination { get; set; }
        public string deviceChannel { get; set; }
        public string deviceChannelType { get; set; }
        public string deviceIdId { get; set; }
        public string displayInCallHistory { get; set; }
        public string duration { get; set; }
        public string e164Destination { get; set; }
        public string enterpriseCallId { get; set; }
        public string eventType { get; set; }
        public string personalPointOfContactId { get; set; }
        public string pointOfContactId { get; set; }
        public string priority { get; set; }
        public string pttDuration { get; set; }
        public string reasonForDisconnect { get; set; }
        public string resourceAORId { get; set; }
        public string ringTime { get; set; }
        public string rolloverAppearance { get; set; }
        public string routedDestination { get; set; }
        public string schemaDifference_blob_reserved { get; set; }
        public string schemaDifference_reserved { get; set; }
        public string startTime { get; set; }
        public string trunkId { get; set; }
        public string trunkBChannel { get; set; }
        public string userId { get; set; }
        public string lastModified { get; set; }
        public string parentUserCDIId { get; set; }
        public string EndTime { get; set; }
        public string EffectiveCallDuration { get; set; }
    }
}
