//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_ticketsoxe
    {
        public int Contador { get; set; }
        public string Ide_TicketsOxe { get; set; }
        public string ChargedUserName { get; set; }
        public string ChargedNumber { get; set; }
        public string CalledNumber { get; set; }
        public sbyte CallType { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public int Duration { get; set; }
        public string PersonalOrBusiness { get; set; }
        public string AccessCode { get; set; }
        public string TrunkIdentity { get; set; }
        public Nullable<int> Ide_Ticket { get; set; }
        public string EffectiveCallDuration { get; set; }
        public string WaitingDuration { get; set; }
        public string CallingNumber { get; set; }
        public Nullable<decimal> ChargedCostCenter { get; set; }
        public string Taxa { get; set; }
        public int Linea_Taxa { get; set; }
    }
}
